# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoMusicfox < Formula
  desc "go-musicfox是musicfox的重写版，使用Go编写的网易云音乐命令行程序。"
  homepage "https://github.com/go-musicfox/go-musicfox"
  version "5.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v5.0.1/go-musicfox_5.0.1_darwin_amd64.zip"
      sha256 "57c93f315709282ed197881c5d485cba252005aaf69645ff52fb90d6e750acf8"

      define_method(:install) do
        system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
        if build.head?
          system 'git', 'fetch', '--tags'
          if OS.mac?
            system "make build BUILD_TAGS='enable_global_hotkey' GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          else
            system "make build GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          end
          bin.install 'bin/musicfox'
        else
          bin.install 'musicfox'
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v5.0.1/go-musicfox_5.0.1_darwin_arm64.zip"
      sha256 "0dbb76f805984c609d0db47a8eb68d9cca9a87165971caa32c7468ce1b6cfaf7"

      define_method(:install) do
        system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
        if build.head?
          system 'git', 'fetch', '--tags'
          if OS.mac?
            system "make build BUILD_TAGS='enable_global_hotkey' GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          else
            system "make build GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          end
          bin.install 'bin/musicfox'
        else
          bin.install 'musicfox'
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v5.0.1/go-musicfox_5.0.1_linux_amd64.zip"
      sha256 "f907fcd902e39788516c11479a9de00fdb3976d620809740e625eae18b574258"
      define_method(:install) do
        system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
        if build.head?
          system 'git', 'fetch', '--tags'
          if OS.mac?
            system "make build BUILD_TAGS='enable_global_hotkey' GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          else
            system "make build GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          end
          bin.install 'bin/musicfox'
        else
          bin.install 'musicfox'
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v5.0.1/go-musicfox_5.0.1_linux_arm.zip"
      sha256 "e0f44a8a0a81d40c797c032b8185fead0a52964289e01d607115e4f47c159732"
      define_method(:install) do
        system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
        if build.head?
          system 'git', 'fetch', '--tags'
          if OS.mac?
            system "make build BUILD_TAGS='enable_global_hotkey' GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          else
            system "make build GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          end
          bin.install 'bin/musicfox'
        else
          bin.install 'musicfox'
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v5.0.1/go-musicfox_5.0.1_linux_arm64.zip"
      sha256 "081ae383be9c7ad180ea300258f395c5648eedc744ed589f811760bb177e916a"
      define_method(:install) do
        system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
        if build.head?
          system 'git', 'fetch', '--tags'
          if OS.mac?
            system "make build BUILD_TAGS='enable_global_hotkey' GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          else
            system "make build GOBINARY=" + ENV["HOMEBREW_PREFIX"] + "/bin/go"
          end
          bin.install 'bin/musicfox'
        else
          bin.install 'musicfox'
        end
      end
    end
  end

  head "https://github.com/go-musicfox/go-musicfox.git"
  depends_on "go", "git" => :build if build.head?
end
