# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spotifox < Formula
  desc "Spotifox is yet another spotify CLI client."
  homepage "https://github.com/go-musicfox/spotifox"
  version "1.0.0-alpha"

  depends_on "terminal-notifier" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.0-alpha/spotifox_1.0.0-alpha_darwin_arm64.zip"
      sha256 "6509fd05c18871a4d76061c3fc48a5f77020e93fd11bb2a3ff26246946b5e534"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.0-alpha/spotifox_1.0.0-alpha_darwin_amd64.zip"
      sha256 "0298f250c063d6b3a2c233f79d85c7d79868e59fb065b8689e6e43513174737c"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.0-alpha/spotifox_1.0.0-alpha_linux_arm64.zip"
      sha256 "79848b2d051cb93464347193e1a4e008e17b6e310cc6a16a0b5bc2b91a489352"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.0-alpha/spotifox_1.0.0-alpha_linux_amd64.zip"
      sha256 "24dec321c9cb806de157fd860f05db7d84cb14b7a87bd5d34463efcae2080f37"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.0-alpha/spotifox_1.0.0-alpha_linux_arm.zip"
      sha256 "f902469588af9490eb4bdf04bc4f90084bcdaa3842f92fb5e0c1bada23c29039"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
  end
end
