# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spotifox < Formula
  desc "Spotifox is yet another spotify CLI client."
  homepage "https://github.com/go-musicfox/spotifox"
  version "1.0.1"

  depends_on "terminal-notifier" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.1/spotifox_1.0.1_darwin_arm64.zip"
      sha256 "86649e928b8aae45f1cccda8aeebb79e7154cad0cf84c9b4bce5d4a1e53dc116"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.1/spotifox_1.0.1_darwin_amd64.zip"
      sha256 "1652463ffcc1e2c37eb1b18cea03423879578204b3c826b3a24a710ffe79bb7c"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.1/spotifox_1.0.1_linux_arm64.zip"
      sha256 "4762b122116ce3e3d9e4fecac7c5e68c36705a712e1143886cd13b9e8f7d69b4"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.1/spotifox_1.0.1_linux_amd64.zip"
      sha256 "0a91be1ba30c9a7e3d37aba6f23a33df9fa7dd152a77c5b3b6b858a1d548045b"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/go-musicfox/spotifox/releases/download/v1.0.1/spotifox_1.0.1_linux_arm.zip"
      sha256 "b1d8ec1f83470ce1aff12461a7ef0ac4b45ad02f8d472aa2af94953483a1503c"

      def install
        system 'echo', '-e', "\033[1;33mStar✨ Please~\033[0m \033[4;36mhttps://github.com/go-musicfox/spotifox \033[0m"
        bin.install 'spotifox'
      end
    end
  end
end
