# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-musicfox" do
  desc "go-musicfox是musicfox的重写版，使用Go编写的网易云音乐命令行程序。"
  homepage "https://github.com/go-musicfox/go-musicfox"
  version "4.8.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "musicfox"

  on_macos do
    on_intel do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.8.4/go-musicfox_4.8.4_darwin_amd64.zip"
      sha256 "6289bd1f2dea7ad78735d81ea2347f4a2333a817ff72b4be53f6f11c51b6d0fb"
    end
    on_arm do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.8.4/go-musicfox_4.8.4_darwin_arm64.zip"
      sha256 "68b5adbbe69ab6c386c9a66b1fd8bd9bdbceeeddf4d11e438429f0150928be58"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.8.4/go-musicfox_4.8.4_linux_amd64.zip"
      sha256 "d1d58afbc62f6e0f1f9819a9f2ac2c628703b8eff50688601ba5c59785a1cdaa"
    end
    on_arm do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.8.4/go-musicfox_4.8.4_linux_arm64.zip"
      sha256 "750f6942972c26bcdf73802d23c71480fa8c61358090e4e465d150cd71a63873"
    end
  end

  postflight do
    system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
  end

  # No zap stanza required
end
