# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-musicfox" do
  desc "go-musicfox是musicfox的重写版，使用Go编写的网易云音乐命令行程序。"
  homepage "https://github.com/go-musicfox/go-musicfox"
  version "4.6.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "musicfox"

  on_macos do
    on_intel do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.6.5/go-musicfox_4.6.5_darwin_amd64.zip"
      sha256 "1c7def76aa9ef3e1e69d86c13e867d52b601de4cae4fc6d443a24828a68f86d2"
    end
    on_arm do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.6.5/go-musicfox_4.6.5_darwin_arm64.zip"
      sha256 "f8c257d4129f8cc7e11c51b53ad2368863391d688fe01c032d8cf9e63a5c9fd0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.6.5/go-musicfox_4.6.5_linux_amd64.zip"
      sha256 "9f71f33781b4366cce30cc05cedd83185a27a3c964d59b1779723957d478b6f0"
    end
    on_arm do
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v4.6.5/go-musicfox_4.6.5_linux_arm64.zip"
      sha256 "eda7548542ba810b9133e57ab473df9ef8e83122632ee55dad4b9b5b8611c8bb"
    end
  end

  postflight do
    system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
  end

  # No zap stanza required
end
