# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-musicfox-macapp" do
  version "5.0.2"

  on_macos do
    on_intel do
      sha256 "1bfe0e74b0602811a3f4eb7f3480a5cd2ceaa995ebed9e376b36f5fe57b5ecea"
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v#{version}/go-musicfox_#{version}_darwin_amd64_macapp.zip"
    end
    on_arm do
      sha256 "0217976c263e7dfb6f896ee1df7e356a787490f89709f8bd4648245f7f343527"
      url "https://github.com/go-musicfox/go-musicfox/releases/download/v#{version}/go-musicfox_#{version}_darwin_arm64_macapp.zip"
    end
  end

  name "go-musicfox-macapp"
  desc "go-musicfox MacApp版本，使用Go编写的网易云音乐命令行程序。"
  homepage "https://github.com/go-musicfox/go-musicfox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "musicfox.app/Contents/MacOS/musicfox"

  postflight do
    system 'xattr', '-r', '-d', 'com.apple.quarantine', '--', "#{caskroom_path}/#{version}/musicfox.app"
    system 'echo', '-e', "\033[1;33m给个star✨吧~\033[0m \033[4;36mhttps://github.com/go-musicfox/go-musicfox \033[0m"
  end

  # No zap stanza required

end
